# See README.md for how to acquire a token

[Protocols.Discord]
# enabled = true  # Uncomment to enable
token = "<token>"

# Only one interface can be enabled at a time
# The first enabled interface will be selected
[Interfaces.Bash]
enabled = true  # Uncomment to enable
