[Protocols.Discord]
# enabled = true  # Uncomment to enable

# See README.md for how to acquire a token
token = "<token>"


# Only one interface can be enabled at a time
# The first enabled interface will be selected
[Interfaces.ZettSH]
enabled = true

# Mode to start in
# Valid values "insert", "normal", and "visual"
# Users experienced with vim may prefer "normal"
mode = "insert"
